name: Run Tests

on:
  workflow_dispatch
  
jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Clone Backend Repo
      uses: actions/checkout@v2
      with:
        repository: health-management-system/hms-backend-express
        path: backend/
    - name: Start the Server
      with:
        run: |
          cd backend
          npm i
          npm run dev
